Construction
dannyrhubarb/utopia pull request #1
Opened 2021-11-06 12:11 UTC by dannyrhubarb

2021-11-06 12:14 UTC, dannyrhubarb commented on src/main/java/Province.java
> +        resources = new Resources();
Prepared for resources. Should resources take Land as dependency?

2021-11-06 13:08 UTC, phiwer commented on src/main/java/Province.java
> +    private static final int BUILDING_DESTRUCTION_TIME = 12;
This is instant

2021-11-06 13:08 UTC, phiwer commented on src/test/java/TestProvince.java
> +        assertEquals(initialBarrenLand, province.getUndevelopedLand());
SHould this also be called barrenLand?

2021-11-06 13:08 UTC, phiwer commented on src/test/java/TestProvince.java
> +        assertEquals(buildingsUnderConstruction, province.getBuildingsInProgress());
buildingsInProgress or other way around?

2021-11-06 13:08 UTC, phiwer commented on src/test/java/TestProvince.java
> +                new Building.Request(Building.FARMS, numberOfBuildings)
I really like this! I will steal this way of constructing a building request as I am not satisified with mine :)

2021-11-06 13:10 UTC, phiwer commented on src/main/java/Building.java
> +    public static final class Request {
record?

2021-11-06 13:17 UTC, dannyrhubarb commented on src/test/java/TestProvince.java
> +        assertEquals(initialBarrenLand, province.getUndevelopedLand());
Yep, probably. Been experimenting with the terminology

2021-11-06 13:18 UTC, dannyrhubarb commented on src/main/java/Building.java
> +    public static final class Request {
Yes! I have Java 14 by default so I have to upgrade though

2021-11-06 13:19 UTC, dannyrhubarb commented on src/test/java/TestProvince.java
> +        assertEquals(buildingsUnderConstruction, province.getBuildingsInProgress());
You mean choose one or the other? This is the result of refactoring to try different terminologies

2021-11-06 13:21 UTC, dannyrhubarb commented on src/main/java/Province.java
> +    private static final int BUILDING_DESTRUCTION_TIME = 12;
You managed to comment on an old commit here?

2021-11-08 08:10 UTC, phiwer commented on src/main/java/Province.java
> +        resources = new Resources();
The income formula is quite complicated though:

Raw Income = (3 * Employed Peasants) + (1 * Unemployed Peasants) + (0.75 * Prisoners) + (Banks * 25 * BE)

Modified Income = Raw Income * Plague * Riots * Bank % Bonus * Income Sci * Honor Income Mod 
                  * Race Mod * Personality Mod * Dragon * Ritual

Expense formula is as well:

Military Expenses = (((Def specs + Off specs )*0.5) + Elites * 0.75) * Wage Rate * Armouries Bonus * Race Mod * Personality Mod * max(Inspire Army , Hero's Inspiration) * Greed * Bookkeeping Science Effect

2021-11-08 08:12 UTC, phiwer requested changes
Please have a look at my formulas wrt resources.

2021-11-08 20:28 UTC, dannyrhubarb commented on src/main/java/Province.java
> +        resources = new Resources();
Great, thanks!

2021-11-08 20:36 UTC, merged